import {
    Cpu,
    Activity,
    AlertTriangle,
    ArrowRight,
    Radio,
    Sparkles,
    ShieldAlert
} from "lucide-react";

/* ── Accent Color Helpers ── */
function getStateColor(state) {
    if (state === "Emergency") return "#FF453A";
    if (state === "High Stress") return "#FF9F0A";
    if (state === "Concerned") return "#FFD60A";
    return "#30D158";
}

function getRiskColor(risk, urgency) {
    if (risk === "CRITICAL" || urgency >= 90) return "#FF453A";
    if (risk === "HIGH" || urgency >= 70) return "#FF9F0A";
    if (risk === "MODERATE" || urgency >= 40) return "#FFD60A";
    return "#30D158";
}

/* ── Fallback Situation Summaries ── */
function getDefaultSituation(driverState) {
    switch (driverState) {
        case "Emergency":
            return "Driver communication indicates an immediate race-critical event. Immediate pit wall intervention is required.";
        case "High Stress":
            return "Driver workload is elevated with signs of increasing pressure. Current communication indicates deteriorating operating conditions.";
        case "Concerned":
            return "Minor concerns have been identified from driver feedback. Vehicle remains operational but should be monitored.";
        default:
            return "Driver communication is calm, structured, and consistent. No significant operational concern was detected.";
    }
}

/* ── Legacy Report Extractor ── */
function extractExecutiveSummaryFromLegacyReport(text) {
    if (!text || typeof text !== "string") return "";

    const execIndex = text.indexOf("EXECUTIVE SUMMARY");
    if (execIndex === -1) return "";

    const sub = text.slice(execIndex + "EXECUTIVE SUMMARY".length);
    const lines = sub.split("\n");

    const summaryLines = [];
    let started = false;

    for (let i = 0; i < lines.length; i++) {
        const l = lines[i].trim();
        if (!l) continue;

        if (!started) {
            if (l.includes("━━━━") || l.includes("═══") || l.includes("📋")) {
                continue;
            }
            started = true;
        }

        // Stop as soon as we hit the next block divider or next section header
        if (
            l.includes("━━━━") ||
            l.includes("═══") ||
            l.includes("DRIVER METRICS") ||
            l.includes("VEHICLE HEALTH") ||
            l.includes("TELEMETRY") ||
            l.includes("RISK ASSESSMENT") ||
            l.includes("STRATEGY") ||
            l.includes("SUGGESTED") ||
            l.includes("AI CONFIDENCE") ||
            l.includes("FINAL VERDICT") ||
            l.includes("Generated by")
        ) {
            break;
        }

        summaryLines.push(l);
    }

    return summaryLines.join(" ").trim();
}

function extractSituationSummary(aiSummary, driverState) {
    if (!aiSummary || typeof aiSummary !== "string") {
        return getDefaultSituation(driverState);
    }

    let rawText = aiSummary;
    if (rawText.includes("AI ENHANCED BRIEF")) {
        rawText = rawText.split("AI ENHANCED BRIEF")[0];
    }

    // Isolate executive summary from legacy report string
    const execSummary = extractExecutiveSummaryFromLegacyReport(rawText);
    if (execSummary && execSummary.length >= 10) {
        return execSummary;
    }

    // If text does not contain legacy report section headers or ASCII dividers, check clean text
    if (
        !rawText.includes("━━━") &&
        !rawText.includes("═══") &&
        !rawText.includes("EXECUTIVE SUMMARY") &&
        !rawText.includes("VEHICLE HEALTH") &&
        !rawText.includes("TELEMETRY ITEMS")
    ) {
        const cleaned = rawText.trim();
        if (cleaned && cleaned.length >= 10 && !cleaned.startsWith("{")) {
            return cleaned;
        }
    }

    return getDefaultSituation(driverState);
}

function extractAiInsight(aiSummary) {
    if (!aiSummary || typeof aiSummary !== "string" || !aiSummary.includes("AI ENHANCED BRIEF")) {
        return "";
    }
    const part = aiSummary.split("AI ENHANCED BRIEF")[1];
    if (!part) return "";

    const lines = part.split("\n").map(l => l.trim()).filter(Boolean);
    const cleanLines = lines.filter(line => {
        if (line.includes("━━━━") || line.includes("═══")) return false;
        if (line.startsWith("```")) return false;
        if (
            line.includes("DRIVER METRICS") ||
            line.includes("VEHICLE HEALTH") ||
            line.includes("TELEMETRY") ||
            line.includes("Generated by")
        ) return false;
        return true;
    });

    const text = cleanLines.join(" ").trim();
    if (text && !text.startsWith("{")) {
        return text;
    }
    return "";
}

/* ── Main Component ── */
export default function AISummary({ analysis }) {
    if (!analysis) {
        return (
            <div
                className="rounded-2xl p-6 animate-fade-in-up"
                style={{
                    background: "rgba(255, 255, 255, 0.035)",
                    border: "1px solid rgba(255, 255, 255, 0.06)",
                    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.2)"
                }}
            >
                <div className="flex items-center gap-3 mb-4">
                    <div
                        className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0"
                        style={{ background: "rgba(10, 132, 255, 0.1)", border: "1px solid rgba(10, 132, 255, 0.2)" }}
                    >
                        <Cpu size={18} style={{ color: "#0A84FF" }} />
                    </div>
                    <div>
                        <h2 className="text-base font-bold text-white tracking-tight">AI RACE ENGINEER</h2>
                        <p className="text-xs text-zinc-500 font-medium">Automated Driver Communication Analysis</p>
                    </div>
                </div>
                <p className="text-xs text-zinc-400">
                    Awaiting radio analysis. Upload or record audio to generate the AI Race Engineer report.
                </p>
            </div>
        );
    }

    const driver = analysis.driver_analysis || {};
    const emotion = analysis.emotion || {};

    const driverState = driver.driver_state || emotion.driver_state || "Calm";
    const emotionName = emotion.emotion
        ? (emotion.emotion.charAt(0).toUpperCase() + emotion.emotion.slice(1))
        : "Neutral";

    const confidenceVal = emotion.confidence !== undefined && emotion.confidence !== null
        ? (emotion.confidence <= 1 ? Math.round(emotion.confidence * 100) : Math.round(emotion.confidence))
        : 85;

    const stressVal = driver.stress !== undefined && driver.stress !== null
        ? driver.stress
        : (emotion.stress !== undefined ? emotion.stress : 0);

    const urgencyVal = driver.urgency !== undefined && driver.urgency !== null
        ? driver.urgency
        : (emotion.urgency !== undefined ? emotion.urgency : 0);

    const issues = Array.isArray(driver.issues) ? driver.issues : [];
    const recommendations = Array.isArray(driver.recommendations) ? driver.recommendations : [];

    const riskVal = (driver.risk || (urgencyVal >= 90 ? "CRITICAL" : urgencyVal >= 70 ? "HIGH" : urgencyVal >= 40 ? "MODERATE" : "LOW")).toUpperCase();

    const isEnhanced = (analysis.ai_source || "").toLowerCase() === "gemini";
    const sourceLabel = isEnhanced ? "AI ENHANCED" : "LOCAL ANALYSIS";
    const sourceColor = isEnhanced ? "#BF5AF2" : "#30D158";

    const engineerReply = analysis.engineer_reply || driver.engineer_reply || "No engineer response available.";
    const situationText = extractSituationSummary(analysis.ai_summary || analysis.summary, driverState);
    const aiInsightText = extractAiInsight(analysis.ai_summary || analysis.summary);

    const stateColor = getStateColor(driverState);
    const riskColor = getRiskColor(riskVal, urgencyVal);

    return (
        <div className="space-y-4 animate-fade-in-up">

            {/* 1. HEADER */}
            <div
                className="rounded-2xl p-5 flex items-center justify-between transition-all duration-300"
                style={{
                    background: "rgba(255, 255, 255, 0.035)",
                    border: "1px solid rgba(255, 255, 255, 0.06)",
                    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.25)"
                }}
            >
                <div className="flex items-center gap-3.5">
                    <div
                        className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0"
                        style={{
                            background: "rgba(10, 132, 255, 0.12)",
                            border: "1px solid rgba(10, 132, 255, 0.2)"
                        }}
                    >
                        <Cpu size={20} style={{ color: "#0A84FF" }} />
                    </div>
                    <div>
                        <h2 className="text-base font-extrabold text-white tracking-tight flex items-center gap-2">
                            AI RACE ENGINEER
                        </h2>
                        <p className="text-[11px] text-zinc-400 font-medium tracking-wide">
                            Automated Driver Communication Analysis
                        </p>
                    </div>
                </div>

                <div className="flex items-center gap-2 shrink-0">
                    <div
                        className="flex items-center gap-2 px-3.5 py-1.5 rounded-full"
                        style={{
                            background: `${sourceColor}14`,
                            border: `1px solid ${sourceColor}28`
                        }}
                    >
                        <div
                            className="w-1.5 h-1.5 rounded-full animate-pulse"
                            style={{ background: sourceColor }}
                        />
                        <span
                            className="text-[10px] font-bold tracking-wider uppercase"
                            style={{ color: sourceColor }}
                        >
                            {sourceLabel}
                        </span>
                    </div>
                </div>
            </div>

            {/* 2. TOP METRIC CARDS (4-Column Grid) */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                
                {/* Driver State Card */}
                <div
                    className="rounded-2xl p-4 flex flex-col justify-between"
                    style={{
                        background: "rgba(255, 255, 255, 0.035)",
                        border: "1px solid rgba(255, 255, 255, 0.06)"
                    }}
                >
                    <span className="text-[10px] font-bold uppercase tracking-widest text-zinc-500 mb-2">
                        DRIVER STATE
                    </span>
                    <span
                        className="text-lg font-extrabold uppercase tracking-tight"
                        style={{ color: stateColor }}
                    >
                        {driverState}
                    </span>
                </div>

                {/* Emotion Card */}
                <div
                    className="rounded-2xl p-4 flex flex-col justify-between"
                    style={{
                        background: "rgba(255, 255, 255, 0.035)",
                        border: "1px solid rgba(255, 255, 255, 0.06)"
                    }}
                >
                    <span className="text-[10px] font-bold uppercase tracking-widest text-zinc-500 mb-2">
                        EMOTION
                    </span>
                    <div>
                        <span className="text-lg font-extrabold text-white capitalize block">
                            {emotionName}
                        </span>
                        <span className="text-[11px] font-medium text-zinc-400">
                            {confidenceVal}% confidence
                        </span>
                    </div>
                </div>

                {/* Stress Card */}
                <div
                    className="rounded-2xl p-4 flex flex-col justify-between"
                    style={{
                        background: "rgba(255, 255, 255, 0.035)",
                        border: "1px solid rgba(255, 255, 255, 0.06)"
                    }}
                >
                    <span className="text-[10px] font-bold uppercase tracking-widest text-zinc-500 mb-2">
                        STRESS
                    </span>
                    <span
                        className="text-lg font-extrabold"
                        style={{ color: stressVal >= 70 ? "#FF453A" : stressVal >= 40 ? "#FF9F0A" : "#30D158" }}
                    >
                        {stressVal}%
                    </span>
                </div>

                {/* Urgency Card */}
                <div
                    className="rounded-2xl p-4 flex flex-col justify-between"
                    style={{
                        background: "rgba(255, 255, 255, 0.035)",
                        border: "1px solid rgba(255, 255, 255, 0.06)"
                    }}
                >
                    <span className="text-[10px] font-bold uppercase tracking-widest text-zinc-500 mb-2">
                        URGENCY
                    </span>
                    <span
                        className="text-lg font-extrabold"
                        style={{ color: urgencyVal >= 70 ? "#FF453A" : urgencyVal >= 40 ? "#FF9F0A" : "#30D158" }}
                    >
                        {urgencyVal}%
                    </span>
                </div>

            </div>

            {/* Row 2: Situation & Risk Assessment */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">

                {/* 3. SITUATION CARD */}
                <div
                    className="lg:col-span-2 rounded-2xl p-5 flex flex-col justify-between"
                    style={{
                        background: "rgba(255, 255, 255, 0.035)",
                        border: "1px solid rgba(255, 255, 255, 0.06)"
                    }}
                >
                    <div className="flex items-center gap-2 mb-3">
                        <Activity size={14} style={{ color: "#0A84FF" }} />
                        <span className="text-[10px] font-bold uppercase tracking-widest text-zinc-400">
                            SITUATION
                        </span>
                    </div>
                    <p className="text-xs leading-relaxed text-zinc-200 font-normal">
                        {situationText}
                    </p>
                </div>

                {/* 5. RISK ASSESSMENT CARD */}
                <div
                    className="rounded-2xl p-5 flex flex-col justify-between"
                    style={{
                        background: "rgba(255, 255, 255, 0.035)",
                        border: "1px solid rgba(255, 255, 255, 0.06)"
                    }}
                >
                    <div className="flex items-center gap-2 mb-2">
                        <ShieldAlert size={14} style={{ color: riskColor }} />
                        <span className="text-[10px] font-bold uppercase tracking-widest text-zinc-400">
                            RISK ASSESSMENT
                        </span>
                    </div>

                    <div>
                        <div className="flex items-baseline justify-between mb-2">
                            <span className="text-xl font-extrabold uppercase tracking-tight" style={{ color: riskColor }}>
                                {riskVal}
                            </span>
                            <span className="text-[11px] font-semibold text-zinc-400">
                                Urgency {urgencyVal}%
                            </span>
                        </div>

                        {/* Thin CSS Progress Bar */}
                        <div className="w-full h-1.5 rounded-full overflow-hidden" style={{ background: "rgba(255, 255, 255, 0.06)" }}>
                            <div
                                className="h-full rounded-full transition-all duration-500"
                                style={{
                                    width: `${Math.min(100, Math.max(0, urgencyVal))}%`,
                                    background: riskColor
                                }}
                            />
                        </div>
                    </div>
                </div>

            </div>

            {/* Row 3: Detected Issues & Strategy */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">

                {/* 4. DETECTED ISSUES CARD */}
                <div
                    className="rounded-2xl p-5 flex flex-col"
                    style={{
                        background: "rgba(255, 255, 255, 0.035)",
                        border: "1px solid rgba(255, 255, 255, 0.06)"
                    }}
                >
                    <div className="flex items-center gap-2 mb-3">
                        <AlertTriangle size={14} style={{ color: issues.length ? "#FF9F0A" : "#30D158" }} />
                        <span className="text-[10px] font-bold uppercase tracking-widest text-zinc-400">
                            DETECTED ISSUES
                        </span>
                    </div>

                    {issues.length > 0 ? (
                        <div className="space-y-2">
                            {issues.map((issue, idx) => (
                                <div
                                    key={idx}
                                    className="flex items-center gap-2.5 px-3.5 py-2.5 rounded-xl"
                                    style={{
                                        background: "rgba(255, 159, 10, 0.06)",
                                        border: "1px solid rgba(255, 159, 10, 0.12)"
                                    }}
                                >
                                    <span className="text-amber-400 text-xs shrink-0">⚠</span>
                                    <span className="text-xs font-medium text-zinc-200">
                                        {issue}
                                    </span>
                                </div>
                            ))}
                        </div>
                    ) : (
                        <div
                            className="flex items-center gap-2.5 px-3.5 py-2.5 rounded-xl"
                            style={{
                                background: "rgba(48, 209, 88, 0.06)",
                                border: "1px solid rgba(48, 209, 88, 0.12)"
                            }}
                        >
                            <span className="text-emerald-400 text-xs shrink-0">✓</span>
                            <span className="text-xs font-medium text-zinc-300">
                                No active issues detected.
                            </span>
                        </div>
                    )}
                </div>

                {/* 6. STRATEGY RECOMMENDATIONS CARD */}
                <div
                    className="rounded-2xl p-5 flex flex-col"
                    style={{
                        background: "rgba(255, 255, 255, 0.035)",
                        border: "1px solid rgba(255, 255, 255, 0.06)"
                    }}
                >
                    <div className="flex items-center gap-2 mb-3">
                        <ArrowRight size={14} style={{ color: "#30D158" }} />
                        <span className="text-[10px] font-bold uppercase tracking-widest text-zinc-400">
                            STRATEGY
                        </span>
                    </div>

                    {recommendations.length > 0 ? (
                        <div className="space-y-2">
                            {recommendations.map((rec, idx) => (
                                <div
                                    key={idx}
                                    className="flex items-center gap-2.5 px-3.5 py-2.5 rounded-xl"
                                    style={{
                                        background: "rgba(255, 255, 255, 0.02)",
                                        border: "1px solid rgba(255, 255, 255, 0.05)"
                                    }}
                                >
                                    <span className="text-emerald-400 text-xs shrink-0">→</span>
                                    <span className="text-xs font-medium text-zinc-200">
                                        {rec}
                                    </span>
                                </div>
                            ))}
                        </div>
                    ) : (
                        <div
                            className="flex items-center gap-2.5 px-3.5 py-2.5 rounded-xl"
                            style={{
                                background: "rgba(255, 255, 255, 0.02)",
                                border: "1px solid rgba(255, 255, 255, 0.05)"
                            }}
                        >
                            <span className="text-zinc-500 text-xs shrink-0">→</span>
                            <span className="text-xs font-medium text-zinc-400">
                                No immediate strategy change recommended.
                            </span>
                        </div>
                    )}
                </div>

            </div>

            {/* 7. SUGGESTED ENGINEER REPLY (Inset Card) */}
            <div
                className="rounded-2xl p-5"
                style={{
                    background: "rgba(255, 255, 255, 0.035)",
                    border: "1px solid rgba(255, 255, 255, 0.06)"
                }}
            >
                <div className="flex items-center justify-between mb-3">
                    <div className="flex items-center gap-2">
                        <Radio size={14} style={{ color: "#0A84FF" }} />
                        <span className="text-[10px] font-bold uppercase tracking-widest text-zinc-400">
                            SUGGESTED ENGINEER REPLY
                        </span>
                    </div>

                    <div
                        className="flex items-center gap-1.5 px-2.5 py-1 rounded-full"
                        style={{
                            background: `${sourceColor}14`,
                            border: `1px solid ${sourceColor}24`
                        }}
                    >
                        <Radio size={10} style={{ color: sourceColor }} className="animate-pulse" />
                        <span
                            className="text-[9px] font-bold uppercase tracking-wider"
                            style={{ color: sourceColor }}
                        >
                            {sourceLabel}
                        </span>
                    </div>
                </div>

                {/* Inset Card */}
                <div
                    className="p-4 rounded-xl"
                    style={{
                        background: "rgba(0, 0, 0, 0.3)",
                        border: "1px solid rgba(255, 255, 255, 0.05)"
                    }}
                >
                    <p className="text-xs italic leading-relaxed font-medium text-zinc-200">
                        "{engineerReply}"
                    </p>
                </div>
            </div>

            {/* 8. OPTIONAL AI EXPLANATION */}
            {isEnhanced && aiInsightText && (
                <div
                    className="rounded-2xl p-5"
                    style={{
                        background: "rgba(191, 90, 242, 0.035)",
                        border: "1px solid rgba(191, 90, 242, 0.12)"
                    }}
                >
                    <div className="flex items-center gap-2 mb-2.5">
                        <Sparkles size={14} style={{ color: "#BF5AF2" }} />
                        <span className="text-[10px] font-bold uppercase tracking-widest text-purple-300">
                            AI INSIGHT
                        </span>
                    </div>
                    <p className="text-xs leading-relaxed text-zinc-300 font-normal">
                        {aiInsightText}
                    </p>
                </div>
            )}

        </div>
    );
}
